### ISSUE TITLE
Ex 3 Scéance 2 Non-lin

### ISSUE THREAD

**Issue by dellafailleh** [blegat/LINMA1702-exercices#19]
Il vaudrait pas mieux noter une ligne genre : 
On rajoute les points où le gradient des contraintes est linéairment dépendant. (Ici le point (0,0) )

**Comment by jdewasseige** [comment]
oui on peut ajouter que c'est normal que notre point optimal ne peut pas être trouvé comme ça puisqu'il ne vérifie pas ilgca

**Comment by jdewasseige** [comment]
d'ailleurs il y a une faute c'est "est vérifiée" plutôt que "n'est pas"
